"use server";
import { revalidatePath } from "next/cache";
import { ensureDatabase,getDatabaseClient } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
const t=(f:FormData,k:string)=>String(f.get(k)??"").trim();const b=(f:FormData,k:string)=>f.get(k)==="on";const n=(f:FormData,k:string)=>Math.max(0,Math.round(Number(f.get(k)??0)));
export async function saveSettings(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return{error:"DATABASE_URL غير موجود."};await ensureDatabase();await q`INSERT INTO site_settings(id,brand_name,brand_tagline,announcement,hero_title,hero_description,hero_image,featured_title,offer_title,news_title,show_featured,show_offers,show_news,show_about) VALUES(1,${t(f,"brand_name")||"بسّام"},${t(f,"brand_tagline")},${t(f,"announcement")},${t(f,"hero_title")},${t(f,"hero_description")},${t(f,"hero_image")||null},${t(f,"featured_title")},${t(f,"offer_title")},${t(f,"news_title")},${b(f,"show_featured")},${b(f,"show_offers")},${b(f,"show_news")},${b(f,"show_about")}) ON CONFLICT(id) DO UPDATE SET brand_name=EXCLUDED.brand_name,brand_tagline=EXCLUDED.brand_tagline,announcement=EXCLUDED.announcement,hero_title=EXCLUDED.hero_title,hero_description=EXCLUDED.hero_description,hero_image=EXCLUDED.hero_image,featured_title=EXCLUDED.featured_title,offer_title=EXCLUDED.offer_title,news_title=EXCLUDED.news_title,show_featured=EXCLUDED.show_featured,show_offers=EXCLUDED.show_offers,show_news=EXCLUDED.show_news,show_about=EXCLUDED.show_about,updated_at=now()`;revalidatePath("/");return{success:true};}
export async function saveProduct(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return{error:"DATABASE_URL غير موجود."};await ensureDatabase();const id=n(f,"id"),name=t(f,"name"),category=t(f,"category"),description=t(f,"description"),price=n(f,"price"),image=t(f,"image")||null,featured=b(f,"featured"),visible=b(f,"visible");if(!name||!category)return{error:"الاسم والتصنيف مطلوبان."};if(id)await q`UPDATE products SET name=${name},category=${category},description=${description},price=${price},image=${image},featured=${featured},visible=${visible} WHERE id=${id}`;else await q`INSERT INTO products(name,category,description,price,image,featured,visible) VALUES(${name},${category},${description},${price},${image},${featured},${visible})`;revalidatePath("/");revalidatePath("/store");return{success:true};}
export async function deleteProduct(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return;await ensureDatabase();await q`DELETE FROM products WHERE id=${n(f,"id")}`;revalidatePath("/");revalidatePath("/store");}
export async function saveNews(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return{error:"DATABASE_URL غير موجود."};await ensureDatabase();const id=n(f,"id"),title=t(f,"title"),excerpt=t(f,"excerpt"),content=t(f,"content"),image=t(f,"image")||null,featured=b(f,"featured"),visible=b(f,"visible");if(!title)return{error:"عنوان الخبر مطلوب."};if(id)await q`UPDATE news SET title=${title},excerpt=${excerpt},content=${content},image=${image},featured=${featured},visible=${visible} WHERE id=${id}`;else await q`INSERT INTO news(title,excerpt,content,image,featured,visible) VALUES(${title},${excerpt},${content},${image},${featured},${visible})`;revalidatePath("/");revalidatePath("/news");return{success:true};}
export async function deleteNews(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return;await ensureDatabase();await q`DELETE FROM news WHERE id=${n(f,"id")}`;revalidatePath("/");revalidatePath("/news");}
export async function saveOffer(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return{error:"DATABASE_URL غير موجود."};await ensureDatabase();const id=n(f,"id"),title=t(f,"title"),description=t(f,"description"),image=t(f,"image")||null,href=t(f,"href")||"/store",visible=b(f,"visible");if(!title)return{error:"عنوان العرض مطلوب."};if(id)await q`UPDATE offers SET title=${title},description=${description},image=${image},href=${href},visible=${visible} WHERE id=${id}`;else await q`INSERT INTO offers(title,description,image,href,visible) VALUES(${title},${description},${image},${href},${visible})`;revalidatePath("/");return{success:true};}
export async function deleteOffer(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return;await ensureDatabase();await q`DELETE FROM offers WHERE id=${n(f,"id")}`;revalidatePath("/");}
export async function submitOrder(_:unknown,f:FormData){const q=getDatabaseClient();if(!q)return{error:"الخدمة غير مهيأة حالياً."};await ensureDatabase();const productId=n(f,"product_id"),name=t(f,"customer_name"),phone=t(f,"phone").replace(/\s+/g,""),note=t(f,"note");if(!productId||!name||!phone)return{error:"الاسم ورقم الهاتف مطلوبان."};if(!/^07\d{9}$/.test(phone))return{error:"رقم الهاتف غير صحيح."};await q`INSERT INTO orders(product_id,customer_name,phone,note) VALUES(${productId},${name},${phone},${note})`;return{success:true};}
export async function updateOrderStatus(f:FormData){await requireAdmin();const q=getDatabaseClient();if(!q)return;await ensureDatabase();const status=t(f,"status"),allowed=["pending","confirmed","done","cancelled"];if(!allowed.includes(status))return;await q`UPDATE orders SET status=${status} WHERE id=${n(f,"id")}`;revalidatePath("/admin");}
